### ISSUE TITLE
Title validation allows invalid permlink to be added to broadcast

### ISSUE THREAD

**Issue by tobias-g1** [travelfeed-io/travelfeed-io#115]
**Describe the bug**

If you attempt to create a post with a title with only chars such as "-----" this will cause an error during broadcast, this is because of the stripping of these chars prior to posting within the permlink. 

**To Reproduce**

1. Go to the create post within travel feed.
2. Enter a title that such as "-------"
3. Enter any post body that meets the validation of 250 words.
4. Publish the post
5. Note that the post cannot be created. 

**Expected behavior**
When a user creates an uses a title such as "-----" they should not be able to submit the post until it would create a valid permlink, alternatively the post should be able to be submitted and a permalink is generated by travelfeed. 

**Error Details*

```
error: "server_error"
error_description: "permlink.size() > STEEM_MIN_PERMLINK_LENGTH && permlink.size() < STEEM_MAX_PERMLINK_LENGTH: Permlink is not a valid size."
```

**Request Payload**

```
{"operations":[["comment",{"parent_author":"","parent_permlink":"travelfeed","author":"votezilla","permlink":"","title":"-------------","body":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam sed arcu interdum, luctus augue eget, rhoncus turpis. Etiam id erat non metus mattis pellentesque nec non ante. Nunc eu tristique risus, eget consequat turpis. Cras iaculis sodales justo consequat faucibus. Etiam suscipit vitae risus et gravida. Phasellus eleifend enim quis turpis lacinia, at mollis lectus venenatis. In tincidunt accumsan mi, vel finibus lorem eleifend ac. Donec non mi id dui consectetur ultricies. Mauris eu molestie est. Fusce consectetur venenatis nibh, eget lacinia ipsum bibendum a. Nulla libero dui, commodo ac felis non, laoreet sagittis dui. Ut vehicula est a tellus suscipit, id lobortis ex interdum. Ut sed luctus eros, non rhoncus libero. Vivamus eu commodo dolor.\n\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam sed arcu interdum, luctus augue eget, rhoncus turpis. Etiam id erat non metus mattis pellentesque nec non ante. Nunc eu tristique risus, eget consequat turpis. Cras iaculis sodales justo consequat faucibus. Etiam suscipit vitae risus et gravida. Phasellus eleifend enim quis turpis lacinia, at mollis lectus venenatis. In tincidunt accumsan mi, vel finibus lorem eleifend ac. Donec non mi id dui consectetur ultricies. Mauris eu molestie est. Fusce consectetur venenatis nibh, eget lacinia ipsum bibendum a. Nulla libero dui, commodo ac felis non, laoreet sagittis dui. Ut vehicula est a tellus suscipit, id lobortis ex interdum. Ut sed luctus eros, non rhoncus libero. Vivamus eu commodo dolor.\n\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam sed arcu interdum, luctus augue eget, rhoncus turpis. Etiam id erat non metus mattis pellentesque nec non ante. Nunc eu tristique risus, eget consequat turpis. Cras iaculis sodales justo consequat faucibus. Etiam suscipit vitae risus et gravida. Phasellus eleifend enim quis turpis lacinia, at mollis lectus venenatis. In tincidunt accumsan mi, vel finibus lorem eleifend ac. Donec non mi id dui consectetur ultricies. Mauris eu molestie est. Fusce consectetur venenatis nibh, eget lacinia ipsum bibendum a. Nulla libero dui, commodo ac felis non, laoreet sagittis dui. Ut vehicula est a tellus suscipit, id lobortis ex interdum. Ut sed luctus eros, non rhoncus libero. Vivamus eu commodo dolor.","json_metadata":"{\"tags\":[\"travelfeed\"],\"app\":\"travelfeed/1.0.0\",\"community\":\"travelfeed\",\"image\":[],\"links\":[],\"users\":[]}"}]]}

```

**Comment by tiotdev** [comment]
Thanks for this! Do you know where I can find the specifications that a permlink has to fulfil in order to be considered valid?

**Comment by tobias-g1** [comment]
@tiotdev Apologies should have added that, a valid permlink consists of A-Z, 0 - 9 or "-" all other characters are invalid.

**Comment by tiotdev** [comment]
@tobias-g1 Since a combination of only `-` is invalid, do you know of any other combinations that are invalid? Do you know if there is a min/max length (1-256 chars?) for the permlink?

**Comment by tobias-g1** [comment]
Not sure if you mean in your current validation, if so !, % or # would cause it to pass an invalid permlink to, as I believe you're stripping those prior to sending. I see certain things such $ and & would work as they're replaced with A-Z characters.  It's only going to occur when a user doesn't enter a valid A - Z or 0 - 9 in the current circumstances.

Yes, min of 1 and max of 255. 

If I didn't get the questions, let me know 🤪

**Comment by tiotdev** [comment]
Fix will be merged into master later this week
