### ISSUE TITLE
Location is not restored when editing post

### ISSUE THREAD

**Issue by tiotdev** [travelfeed-io/travelfeed-io#129]
When editing a post with a location, the location picker has no location set by default. It should have the existing location set by default.

**Comment by for91days** [comment]
Someone else was mentioning that he can't edit locations at all!

**Comment by tiotdev** [comment]
Fixed in https://github.com/travelfeed-io/travelfeed-io/commit/24a11bef32ce9184913dbeed51580e80de944b30
