### ISSUE TITLE
Simplify Video Integration

### ISSUE THREAD

**Issue by for91days** [travelfeed-io/travelfeed-io#140]
Our editor doesn't accept code via copy and paste the embed html youtube provides. Best would be a block option where you can chose video as the media and then being able to just post the video url from various video platforms.

**Comment by tiotdev** [comment]
This used to work with editor.js in closed beta, as explained in #67 editor.js is too buggy to be used at the moment. Will be reimplemented at a later point when the devs fix the bug.

**Comment by tiotdev** [comment]
Will be available in the new editor
