### ISSUE TITLE
Remove Blocks

### ISSUE THREAD

**Issue by for91days** [travelfeed-io/travelfeed-io#141]
Any easy way to remove blocks again.

**Comment by tiotdev** [comment]
I don't understand. What do you mean by "blocks"?

**Comment by for91days** [comment]
Within the editor, using the + sign ... from WP I'm used to be just to click on it and I can remove the entire BLOCK (text/images)

**Comment by tiotdev** [comment]
That's what https://editorjs.io/ has that we used in closed Beta. But even if at some points the bugs are fixed, a block based solution is not fully compatible with other Steem frontends. Basically blocks have to be converted to HTML when posting and converted back to blocks when editing, that will be buggy. We could store the blocks in the json_metadata, but then it would not be possible to view/edit the post on other Steem frontends.
