### ISSUE TITLE
Weird Jump In Editor

### ISSUE THREAD

**Issue by for91days** [travelfeed-io/travelfeed-io#150]
> Jürgen and I live by a set of unspoken mutual agreements. Number 14 states: once we’ve started debating whether to leave a place … be it a restaurant, a movie, a cafe, or a party… we should just immediately leave. And that goes for hotels, too. When we checked into our Elmina hotel, we were immediately displeased. But did we really want to put ourselves through the agony of finding another hotel at the last minute? But as soon as the question was asked, it was answered, thanks to Mutual Agreement #14. So, we spent 30 agonizing minutes searching… and then a full week enjoying the fruits of our decision: a stay at Coconut Grove.

When I copy and paste this text in the Easy Editor .... for some reason the cursor jumps to #14 instead of the end of the text block.

**Comment by tiotdev** [comment]
The editors will be fully replaced
