### ISSUE TITLE
Remove Shodows

### ISSUE THREAD

**Issue by steemdevelopment** [travelfeed-io/travelfeed-io#160]
Turn .MuiPaper-elevation1 box-shadow  into `box-shadow: 0px 1px 1px 0px rgba(0, 0, 0, 0.2),0px 1px 1px 0px rgba(193, 193, 193, 0.14),0px 1px 1px -1px rgba(0, 0, 0, 0.12);` it will make the design look much cleaner on the computer and ipads.

You guys are over using shadows, you need to lower the px of your box shadows a bit. I understand it comes like this naturally in material design or some bootstrap packages. But its sort of throwing things off.

**Comment by tiotdev** [comment]
You are right, that does look better. Just changed it, should be live on https://staging.travelfeed.io/ in a few minutes. Thank you!

**Comment by steemdevelopment** [comment]
No problem, and yeah it looks good.
