### ISSUE TITLE
Gifs Not Supported On TF.io

### ISSUE THREAD

**Issue by for91days** [travelfeed-io/travelfeed-io#173]
**Describe the bug**
Gifs are not animated on TF

**To Reproduce**
See embedded gif here: https://travelfeed.io/@justinparke/or-an-immigrants-tale-or-the-khmerican-family-abroad-or-3-the-great-ecuador-exodus-pt-2-or

**Expected behavior**
It's just stuck

**Comment by for91days** [comment]
Reported by: justinparke

**Comment by tiotdev** [comment]
This is due to steemitimages that converts gif to other formats in our implementation. 

To solve this, the regex `<img src="([^"]*)"(?:| alt="([^"]*)") \/>` has to be changed to exclude .gif files. Should be possible to solve this using https://regex101.com/,
