### ISSUE TITLE
Tables Are Off on TF.io

### ISSUE THREAD

**Issue by for91days** [travelfeed-io/travelfeed-io#174]
**Describe the bug**
User brought forward that he wrote on article on TF.io, implemented tables but had to go back and forth between our editor and the Steemit editor. On steemit it looks much more pleasing than on TF.io

**To Reproduce**
Compare these two urls ... the table is towards the beginning of the article: 

https://travelfeed.io/@justinparke/or-an-immigrants-tale-or-the-khmerican-family-abroad-or-3-the-great-ecuador-exodus-pt-2-or

https://steemit.com/travel/@justinparke/or-an-immigrants-tale-or-the-khmerican-family-abroad-or-3-the-great-ecuador-exodus-pt-2-or?sort=new#comments

**Comment by for91days** [comment]
Reported by justinparke

**Comment by tiotdev** [comment]
TravelFeed is primarily for posts created through TravelFeed. This means that we don't support certain formatting/custom HTML hacks that might work or not work on some other frontends, at the same time these frontends might not support formatting that is possible on TravelFeed.
Tables work fine when they are used as they are supposed to: https://travelfeed.io/@jpphoto/nice-post
