### ISSUE TITLE
Flag / Delete Comments - From Our Platform

### ISSUE THREAD

**Issue by for91days** [travelfeed-io/travelfeed-io#180]
Need a way to flag and remove comments from travelfeed.io

**Comment by tiotdev** [comment]
There already is for curators. Do you mean hiding posts when they are downvoted on other dApps or when users have a low rep?

**Comment by for91days** [comment]
For example on our Easylogin post there was someone leaving a comment with a Referral link - on Steemit.com it was collapsed and greyed out and on our end (TF.IO) it was still fully visible. I tried to  go back and find the comment but it seems to be gone now. So what I mean for our end. Curators having the power to fully delete comments from our frontend and our users alerting us to comments.

**Comment by tiotdev** [comment]
Should we fully hide hidden comments or grey them like Steem? Or hide no posts hidden on Steem but introduce a function for reporting?

**Comment by for91days** [comment]
I like fully hiding them ..
